### ISSUE TITLE
Kashyyyk Arena Challenge

### ISSUE THREAD

**Issue by Tekaoh** [SWG-Source/dsrc#1]
<strike>As per a conversation in Discord, it seems that you need to have the `space_kashyyyk` zone enabled in order to complete the Arena Challenge. This is presumably because `script.library.space_dungeon` is imported and then used by several .java files involved in running the arena.

For now, a workaround is to make sure that the space zone is loaded when trying to complete that quest. A longer term workaround would be to figure out how to make `script.library.space_dungeon` available after loading `kashyyyk_main` to eliminate the unexpected behavior.

**Comment by Tekaoh** [comment]
From @Cekis on Discord:

just a quick update on the Kashyyyk quest Arena bug...
I've narrowed it down to a simple call that puts an objvar on the player... sometimes it succeeds, sometimes it doesn't...
now, the problem is that the server is supposed to process all "messageTo" calls successfully... however, some are guaranteed and some are not (set via a T/F value)
this problem is that they're not guaranteed... and they're sometimes getting there and sometimes not... but odd that the server would "drop" messages.
since Legends hasn't ever had this issue (for real? it was on live?), I can only assume we did something at SB that would cause them to "fall off", but this is the FIRST evidence I've ever seen of that happening...
and it's honestly very likely to happen... so that's odd too.
at any rate, I could fix the code for this instance to work 100%, but I'm doubting that's the core issue and some investigation needs to be done into why the server is "dropping" non-guaranteed messageTo calls.
the other odd thing is that when it works, it always works...
and when it fails, it MOSTLY fails.

**Comment by Cekis** [comment]
To add to this... seems this is an issue only when sending messageTo's from an object on one server to an object on a different server.

**Comment by Cekis** [comment]
I just fixed this.  Here's what was happening... basically it was a race condition.  The system tried to set obj vars on the player(s) by way of sending a message to the player.  That message SOMETIMES didn't get to the player before the player was transported into the instance.  The instance has a check for that obj var and if it doesn't find it, it boots the player from the instance.
What I did was set that obj var directly on the player before attempting to warp the player instead of relying on the message transport/execution time.  This removed the race condition.  I also did some cleanup here and there too, but the offending lines were near line 835 or so in the space_dungeon.java file.
