### ISSUE TITLE
Tie Interceptor / Advanced Stuck In The Ground At Space Ports

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#123]
A tie advanced keeps getting "stuck" into the ground in start ports, you can't select it and it doesn't move nor does it have collision
![screenShot0123](https://user-images.githubusercontent.com/55237094/82757706-2fe21b00-9dda-11ea-9e78-bb514f2be5ab.jpg)
![screenShot0122](https://user-images.githubusercontent.com/55237094/82757707-3375a200-9dda-11ea-8cda-e0857e1c8210.jpg)
![screenShot0092](https://user-images.githubusercontent.com/55237094/82757714-3d97a080-9dda-11ea-9dba-53e030586197.jpg)

**Comment by IrishDarkshadow** [comment]
The TFE guys had a similar issue and it turned out to be an entry in the Oracle database that was spawning the ship. I wasn't able to reproduce the issue on the QA server or a master branch VM.

**Comment by Namsemag** [comment]
Right any idea where to start to look for the reason?

**Comment by IrishDarkshadow** [comment]
Three recent pieces of information on this one:

(1) god client cannot target the Tie to get spawn info from it
(2) it only appears when a city / region flips to Imperial GCW control
(3) as it has no OID, the suspicion is that it might be a client effect for flyby traffic that is spawning in the wrong place

**Comment by Cekis** [comment]
This is likely the flyby file then that is causing the TIE to show up in the middle of the starport.  The file is spawned based on faction alignment...  If it is only showing up when imperial control is in place then this file is spawned:  

object/static/structure/general/distant_ship_controller_imperial.cdf

There is likely something in that chain that is putting the tie there.  We know it's an aggressor, so it's likely that particular model in that CDF which is not being assigned the correct aspect of "flying by".

**Comment by IrishDarkshadow** [comment]
The original report of this was a TIE Interceptor, the first pic in this bug report is a TIE Advanced and the current one in Mos Espa on the QA Server is an Interceptor too.

Did you get an Aggressor to spawn somewhere else?

**Comment by Cekis** [comment]
The best way to test this is to spawn that IFF somewhere alone (i.e. out in the desert) and see if the tie shows up at the spawn point.  If it does, then yeah, the CDF needs fixed.

**Comment by IrishDarkshadow** [comment]
Used this: 
/object spawn object/static/structure/general/distant_ship_controller_imperial.iff

Produced this:
![image](https://user-images.githubusercontent.com/12293802/93377085-75779780-f852-11ea-9634-a728f05e9ebf.png)

**Comment by IrishDarkshadow** [comment]
The fix to this issue is in this commit: https://github.com/SWG-Source/client-assets/commit/ef3dc694d2b120b20f0aa8c03e013fe9755ea90a

The appearance file for the imperial controller had mismatched entries in it for the skeletion and animation table (skt / lat) related to the TIE Interceptor. It was originally using distant_tie_interceptor and distant_tie_interceptor1 in the SKTI chunk but the LATX chunk was using distant_tie_interceptor1 and distant_tie_interceptor2. Changing those two chunks so that they match up stops the half buried ship from appearing in the center of a starport that is in an Imperial controlled GCW region.

I watched the air traffic after applying this fix and was able to observe every combination of ships attached to the controller except for a single TIE Interceptor....the double and triple formations showed up multiple times. That may result in a following on issue to be solved but for now, this fix corrects the reported issue.
