### ISSUE TITLE
"Missing Values" on Various Spawners around the Galaxy

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#128]
First spotted by Aconite and confirmed by me

![screenShot0142](https://user-images.githubusercontent.com/55237094/83172027-e01f8e80-a10e-11ea-8674-88263b9f0e5c.jpg)

**Comment by AconiteGodOfSWG** [comment]
perhaps let's make this a master ticket of spawners with missing values... found more here:

3593 -5033

![image](https://user-images.githubusercontent.com/63141077/83464601-f7c08500-a436-11ea-8918-7bdcf630d5d9.png)

**Comment by Namsemag** [comment]
![screenShot0149](https://user-images.githubusercontent.com/55237094/83552273-6538e800-a501-11ea-9c7a-bf9b5850f00c.jpg)

Found more on Corellia

**Comment by Cekis** [comment]
FYI, these are likely TAB file fixes.

**Comment by IrishDarkshadow** [comment]
That tatooine_worrts spawner is coming from tatooine_6_2.tab .....nothing in there is using a "size" value from what I've seen so far. 

The worrts file itself is very basic....creature name, number of them. The buildout file has the spawner parameters as objvars.

Will dig around some more and see why the message is popping up in god mode regarding "MISSING VALUES".

**Comment by IrishDarkshadow** [comment]
The check it's doing is this:
if (fltSizes.length != strSpawns.length)
            {
                setName(self, "MISSING VALUES: Each spawn must have an associated size (" + strFileName + ")");

The entry in the buildout tab does have a value for strSpawns (4) which matches the tatooine_worrts spawner tab but there is no value for fltSize present. 

Only one entry in that buildout has a value for fltSize and it's a POI entry.

**Comment by Cekis** [comment]
This is happening because the default spawner file (the spawner TAB file) has an extra "blank" entry in it.  The spawner looks through that file and finds out what kind of things can be spawned when that file is called - then chooses a random value from that list and makes a spawn from it.  This would allow the spawner to choose a random thing to spawn from that list the next time it decides to spawn something.  Most of the files contain only one entry so it's generally static (i.e. "worrts" in "tatooine_worrts.tab").  
The spawner grabs a random spawn without a default choice, but then chooses a NON-RANDOM default quantity. What's odd to me is why they would code it in this way.  I feel somebody just missed sync'ing a random name with a random value.  Because of this, the spawner is realizing the total number of spawns (strItem) is not equal to the total number of quantities (fltSize) found in the file.
The fix is to simply sync the random spawns with the random quantities
