### ISSUE TITLE
Missing Food and Chemical Tool Schematic from Trader

### ISSUE THREAD

**Issue by hugoswg** [SWG-Source/dsrc#137]
Problem: When u start as new trader, you should recieve the schematic of the Food and Chemical Tool at lvl 4. Neither on my baremetal install nor the VM i get it from the start. In order to get it, you need to respec first.

How to replicate: Create a new Trader, grind to level 4, you don´t get the schematic. Respec to recieve it.

Tested with: baremetal install, fresh VM and a newly cloned Client.

![correct](https://user-images.githubusercontent.com/69413070/89726230-7843c900-da18-11ea-843b-7dec568a004c.jpg)
![wrong](https://user-images.githubusercontent.com/69413070/89726231-78dc5f80-da18-11ea-93bb-4a25dc89f6f1.jpg)

**Comment by IrishDarkshadow** [comment]
Just ran a test on a fresh VM. Created a new domestics trader, skipped the tutorial and spawned in Mos Eisley as a cl6. This is what I get:
![image](https://user-images.githubusercontent.com/12293802/93069915-1eb56680-f676-11ea-913e-5f965fe0e897.png)

**Comment by IrishDarkshadow** [comment]
Just created a fresh trader and ran the tutorial to hit cl4 "naturally" and I get this:
![image](https://user-images.githubusercontent.com/12293802/93071927-aa2ff700-f678-11ea-8991-745f5a817f44.png)

The schematic is being provided as expected whether you run the tutorial and craft to cl4 or skip it to spawn in Mos Eisely as a cl6. No respec was required and neither character used in these tests has used god mode.

Seems like your issue is something specific to your local environment.
