### ISSUE TITLE
Bubbling Rocks Appearance Changes

### ISSUE THREAD

**Issue by seefo** [SWG-Source/dsrc#20]
appearance changes from https://github.com/SWG-Source/dsrc/commit/a37e827a88bb43452a95b19a2ec760181be3be8f need to be undone, and their server templates updated to have the `skipLosCheck` objvar like https://github.com/SWG-Source/dsrc/commit/5e55513655d497f2929925230cf042b5355d7792

**Comment by IrishDarkshadow** [comment]
The problem here turns out to be two-fold. The server side sys.shared tpfs lack the apt filename (appearance/rock_tiny_purp.apt) but not just for the bubbling rocks, also for the burning, glowing and steaming rocks. 4 collections, 40 files.

The skipLosCheck isn't required to correct the issue. The 40 files in the client (sb-redux_01.tre) are corrupt / truncated. The older, original versions in patch 37 work fine. I'm currently adding the apt reference back into the server side tpfs and lifting the patch 37 IFFs to place them directly into the client as loose files which will override the corrupted versions. The bubbling rock collection works perfectly at that point: 
![bubble_1](https://user-images.githubusercontent.com/12293802/64913502-28da1780-d739-11e9-941b-7156d5cd6183.jpg)
![bubble_2](https://user-images.githubusercontent.com/12293802/64913504-2bd50800-d739-11e9-93aa-20f6a58b32fe.jpg)
![bubble_3](https://user-images.githubusercontent.com/12293802/64913505-2e376200-d739-11e9-8998-1612f1600b4c.jpg)
![bubble_4](https://user-images.githubusercontent.com/12293802/64913508-3b545100-d739-11e9-8dc9-4564910d8003.jpg)
![bubble_5](https://user-images.githubusercontent.com/12293802/64913509-40190500-d739-11e9-836f-f939eb5a9b3a.jpg)
![bubble_6](https://user-images.githubusercontent.com/12293802/64913513-46a77c80-d739-11e9-85fa-5419832ff9f4.jpg)
![bubble_7](https://user-images.githubusercontent.com/12293802/64913516-57f08900-d739-11e9-93c7-dfc624332f25.jpg)
![bubble_8](https://user-images.githubusercontent.com/12293802/64913519-5e7f0080-d739-11e9-973e-51a4ed34ee7d.jpg)
![bubble_9](https://user-images.githubusercontent.com/12293802/64913522-6343b480-d739-11e9-83b2-c663ff268ea8.jpg)
![bubble_10](https://user-images.githubusercontent.com/12293802/64913523-6b035900-d739-11e9-95a0-c563f0508820.jpg)
![bubble_11](https://user-images.githubusercontent.com/12293802/64913524-6fc80d00-d739-11e9-95e1-f2a0fbd4f3d4.jpg)

At a later point the corrupted ones as well as the loose ones can be removed from the client completely.

**Comment by IrishDarkshadow** [comment]
Bubbling, burning, glowing and steaming rock collections all confirmed to be working now.
