### ISSUE TITLE
USV-5 Speeder - Customisation Doesn't work

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/dsrc#22]
https://cdn.discordapp.com/attachments/433006120295071786/556907540173029409/unknown.png

**Comment by TyroneSWG** [comment]
Is this still broken? Tried to color a speeder and said it failed.

**Comment by Cekis** [comment]
Ok Ok Ok... taking a look at this then.

**Comment by Cekis** [comment]
When attempting to use a coloring kit on a USV-5 speeder - either Trim OR Frame - you are only presented with ONE color.  When trying to select that color the player is presented with the following message:
"You have failed customization operations on USV-5 Modified Landspeeder."

**Comment by Cekis** [comment]
A string search in the client file (where a lot of on-screen messages are) shows it comes from the "customizer.stf" file as a key with name "prose_fail".  Doing a search for that file/key combination points to the script.item.tool.vehicle_customizer script directly from the "customizationFailed" method (duh, lol).
The only logical place for that method to be called is in "handleSetCustomization" method in the same file.  That's where I'll focus on gathering more information for now.

**Comment by Cekis** [comment]
Stopping on this for now - please somebody jump in if you have specific knowledge with customization.  It seems the game cannot identify the path of "private/index_color_1" and other pathname/directories.  This would lead me to believe that coloring kits have not worked for some time.  Perhaps a rebuild of the ACM files would resolve this?

**Comment by TyroneSWG** [comment]
The acm isn't packing any pal variables. Rebuilding the ACM doesnt fix this. Currently on my setup, anything that can be hued is default grey.
-------- Original message --------From: Cekis <notifications@github.com> Date: 2/7/20  1:32 AM  (GMT-06:00) To: SWG-Source/dsrc <dsrc@noreply.github.com> Cc: Freddy <freddylikespotatos@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [SWG-Source/dsrc] USV-5 Speeder - Customisation Doesn't work (#22) Stopping on this for now - please somebody jump in if you have specific knowledge with customization.  It seems the game cannot identify the path of "private/index_color_1" and other pathname/directories.  This would lead me to believe that coloring kits have not worked for some time.  Perhaps a rebuild of the ACM files would resolve this?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SWG-Source/dsrc/issues/22?email_source=notifications\u0026email_token=ABKZEAWIIWVKFVR3ETDWU7TRBUE7LA5CNFSM4G7J2ZO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELB7W7A#issuecomment-583269244",
"url": "https://github.com/SWG-Source/dsrc/issues/22?email_source=notifications\u0026email_token=ABKZEAWIIWVKFVR3ETDWU7TRBUE7LA5CNFSM4G7J2ZO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELB7W7A#issuecomment-583269244",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlecH92** [comment]
The USV *should* be a separate issue from the ACM not functioning. Legends had the same issue, turns out the player USV doesn't use a customizable appearance.
In the file `sku.0\sys.shared\compiled\game\datatables\mount\saddle_appearance_map.tab`, we had to edit FROM `lookup/speeder_usv5_s02	5	appearance/speeder_usv5_s02.apt	clientdata/vehicle/speeder_usv5.iff` TO `lookup/speeder_usv5_s02	5	appearance/speeder_usv5.apt	clientdata/vehicle/speeder_usv5.iff` (swapping the appearance/*.apt file)
This was ONLY changed in the saddle_appearance_map used by the ACM process - we did not edit it server side or update the file clientside. I don't know if it would affect things if included there.

**Comment by Cekis** [comment]
this actually explains it.  The APT's were removed in favor of SSA's to save server space.  It seems the server can't have the APT's swapped out for SSA's due to this reason (and likely others).  Will work on reverting this change and going back to APT's as the ACM build process also needs APT's in order to properly rebuild the ACM files.

**Comment by Cekis** [comment]
Hmm... nope... I replaced the XP38 APT such that it pointed to the LOD instead of the SSA and it still failed.  Still unresolved.

**Comment by AlecH92** [comment]
ACM should be targeted at a full client extract from SIE, we build ours via Windows as well.

**Comment by IrishDarkshadow** [comment]
Fixed by creating the LOD file for the s02 variant of the speeder and running an ACM update.
bda47779dd9913c6f2b3420ff4372716dce45d52
