### ISSUE TITLE
Medium Naboo House Style 2 Does Not Deploy/Unpack

### ISSUE THREAD

**Issue by DevilFangs** [SWG-Source/dsrc#274]
Deed exists, & is spawnable, but does not respond when Use Deed is selected from Radial.
![screenShot0017](https://user-images.githubusercontent.com/79380880/108613487-c5352e80-73af-11eb-9a76-39641d42bd0e.jpg)

**Comment by Erusman** [comment]
I went in to look at this issue. However, the problem was that there was never a Naboo Medium Style 2 player house in NGE.  There was of course a style 1 and 2 of the small and large Naboo houses.  You can refer to this link for reference. https://swglegends.com/wiki/index.php?title=Structures  Not sure how this template got into our dsrc. lol.  But, I will delete the .tpf's. and close this issue.

**Comment by MauiDoug** [comment]
Wanted to add to this just for context - I'm pretty sure this was a house that Irish added after finding it in the codebase and seeing it wasn't implemented.
