### ISSUE TITLE
Naboo Space Naboo Space Station

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#48]
the convosation for mecanery missons text it bugged as shown in screenshot
![unknown](https://user-images.githubusercontent.com/353448/65376180-d64aaf00-dc94-11e9-8422-7ea31beaae25.png)

**Comment by IrishDarkshadow** [comment]
Well this one has turned into a bit of an odyssey. The original issue being reported here for the Naboo station merc contracts is due to "mis-numbered" entries in the string files for the conversation options at the station. The strings are present in the final day files we're using in the client, they are just in the wrong "slots" within the files. 

The Legends server seemingly does not have these issues and so I checked out their client. They have an additional, custom tre file (patch 60) in their client. When the string files in that client are compared to the swgsource files side by side, you can see the mis-numbering. In addition, as swgsource has final day string files, there are also extract entries for tier7 merc contracts which have not been restored yet.

The scope of fixing this Naboo bug has therefore broadened to include all stations that are similarly affected. Tomorrow the following approach will be taken:

(1) do all strings look correct
(2) do the strings launch the correct mission based on their text
(3) do the actual missions work. 

Any other bugs detected will get discrete reports on here so they can be pursued to completion in their own right.

**Comment by Cekis** [comment]
Going to fix these by aligning with our current client version.

**Comment by Cekis** [comment]
Latest set of commits have now fixed this... to get the new conversations, you will need to rebuild the java code.
