### ISSUE TITLE
Missing Conversation Text from Rebel Commendation Officer in Restuss (Phase 3)

### ISSUE THREAD

**Issue by Namsemag** [SWG-Source/dsrc#60]
![screenShot0038](https://user-images.githubusercontent.com/55237094/66720732-96409d00-edf8-11e9-8a10-2b224009e1b6.jpg)

See screen shot, option also doesn't seem to do anything.

**Comment by Cekis** [comment]
This has been fixed.  I had to remove the Crusader Armor Dye Kit schematic from the conversation... SOE removed it from the string file in Patch 56 so the final day conversation strings were broken due to the removal.  I would have left it in the conversation script, but the string file for the conversation no longer had the text it was referencing.  Not a mis-alignment, but an all out removal from the string file.
