### ISSUE TITLE
after server reboot all my spawned houses disappeared

### ISSUE THREAD

**Issue by LORDANDERSON** [SWG-Source/dsrc#72]
after server reboot all my spawned houses disappeared

**Comment by IrishDarkshadow** [comment]
Again, there is very little detail here to go on. Are you referring to house deeds that you spawned or actual houses that were placed? what planet(s)? How did you shutdown your server? How long had the houses / deeds been "spawned" before the server reboot?

Providing so little detail about your issue is basically like saying that you saw a UFO and expecting us to understand the how, when and where of that sighting.

**Comment by Tekaoh** [comment]
It sounds to me like he's talking about buildings that he literally `/object spawn`ed.

If that's the case, be aware that anything you spawn in the open world is basically present in RAM only and will not persist through a reboot. You can, however, save your spawned object to the database with the `/object persist` command. Anything manually persisted in this way will survive a reboot. This is great for adding anything to your world including decorative items or even public character builder terminals, for example.
