### ISSUE TITLE
WoD - "Confirmed Dead"  quest (Shrine duplicate spawn)

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#97]
the shrine is a dubble spawn 
![image](https://user-images.githubusercontent.com/353448/79072388-acacb000-7cd8-11ea-8630-a38ecd305dae.png)
https://www.twitch.tv/videos/590129032

**Comment by IrishDarkshadow** [comment]
This duplication is being caused by a second copy of the altar / shrine being spawned in via a clientside buildout file. There are 37 entries in that file for this specific area, when I remove those the second altar disappears....as does every deco object around it.

I'm looking into converting those deco objects into server side spawns as being the real fix to this issue.

**Comment by IrishDarkshadow** [comment]
Fix for now was to remove the duplicated spawn from the client side buildout. Longer term we will need a plan for handling all of these file entries.
